language: python
python:
  - "2.7"
  - "3.2"

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.2"

script:
  - py.test

notifications:
  email: false
  slack:
    secure: "qVbzNehqssfpzbw9ELc3pj4URPd0xj+V+a0ymQ8vA9HKb3B8qmrwljm9bfm+fxdbTwqoxF+B0wyPfvRU0nNYLlyZhwbGsQTRUP9ceTwUhyLoFcVapqCl7on+hk3BCcQREjJcGSTKGpCUvE+XUGNckz3VYo2Wr3k+18qBkwbv6AVUpr4DUuNtrLFs0cQ0ICc4e4XwFOWJk8RisRrekxacjvZwDLHyLwRlxjyRGP4JM24zKB+0FyGObcWtuotjLBA0Lj5uLbFv3TXNEWNuFf3OSon9vDORwMJPFgXR8w+DA28eAkLxQbxSUBJTxKkHJf1OPExzmsksuLbm7vW8/Zjk1tsmhEzUAQ6rlV3038oL9L+fMYYv43Z9W7JzF11dQUm5WIHGJ/2WsF1s0C4glhoDwVPim4CHuV476jkhmHb0oQQypttGNUZKcMiBgTA0YyRY0Km3V3EVhYtzGat+bB731yqo/6Ea2qNCskUnSJSa3ncCFaJsUYxfP3NXlYLvzEGqMOX6qniMRuCdsBdgUspJsZ2KaNV5L9/eCD59Bz4F6q1ratr1dIK7CMM4aSTaHEn3HB8L6WRvl0W0dspNMRgDo614TIFE/38RyxJnY1R3Ms+arIEai1MFI9PhotvsLA/C9LcC+lBXQ3CboYaj0HcXCqHKFKHBDmFkhyfI5ckXbdg="

deploy:
  provider: pypi
  user: tomasbasham
  password:
    secure: "eRGYvrGIOT7STL4zB3MQAhkDlQ6nFpmEOkWDvKBlP3xWwUE5JDFXz9IzYyO58dyL2X2+LNPelmbut1Cue0VXYiaBNy9qMzhk9CNiwjzADWE/xBIjWR+orXxUUHHBiYjiGauVqDxYPEuDpD1esC3s/8H+7n5a61lkO+ahL+lG1/oOkE6S3stPmdCcaFI1tpMM/RqoD3AehQw5n8JbhMGPbrWkBKgLh8Ur9RKgYlLFWOD7GyPXrQBW4/NCY7EviNn5pHhXS70PQ68xsIJ7pYL+4B/PaVa0Vx8dgy4HIkKk7PK+Ui0WygklHnZr2D5J9SUI9Jgb8xyljfVMoAFwFdxHVnTnmGdDezTq6X90lM28YUqT5spQqZQIVWgvOK5KZo64eWe1T1066p5bLhRk1+3oGcF57vgILxp3uG0fl2aviF+SEEd8jXcd0TiNc4WboSooPf7WxQetgo72mmyVSn+6VpbMdD0xS52gbxzS3iJIWWUbuPtGHzD7zMutu7L0tMnfEBKUH6uqWxmJX7eRWYHxkPEB9xLFyiNURFsWhMKTdpGgFPwkTMWQbqnqtcSH1qlfiOY2o/a0eihTQB6HOzGvCHCS6ohj6Jkf+lToYeRDWdsDwocfMg/5I0THDK8m4N2eJyf5wKbV59Ai3ILfkHQzOnzU8QlftCTK+Ag8iKIOpvA="
  on:
    tags: true
    repo: tomasbasham/dominos
